// <auto-generated />
using System;
using DAL.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211215222910_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Entities.EindkwalificatieEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EvlId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvlId");

                    b.ToTable("eindkwalificatie");
                });

            modelBuilder.Entity("DAL.Entities.EvlEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beroepstaken")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Studiepunten")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("evl");

                    b.HasDiscriminator<string>("Discriminator").HasValue("EvlEntity");
                });

            modelBuilder.Entity("DAL.Entities.LeeruitkomstEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EvlId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EvlId");

                    b.ToTable("leeruitkomst");
                });

            modelBuilder.Entity("DAL.Entities.RubricCriteriumEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Oordeel")
                        .HasColumnType("int");

                    b.Property<int>("RubricId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RubricId");

                    b.ToTable("rubric_criterium");
                });

            modelBuilder.Entity("DAL.Entities.RubricEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("MinimaalOordeel")
                        .HasColumnType("float");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TentamineringId")
                        .HasColumnType("int");

                    b.Property<int>("Weging")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TentamineringId");

                    b.ToTable("rubrics");
                });

            modelBuilder.Entity("DAL.Entities.TentamineringEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aanmeldingstype")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EvlId")
                        .HasColumnType("int");

                    b.Property<string>("Hulpmiddelen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("MinimaalOordeel")
                        .HasColumnType("float");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tentamenvorm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Weging")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvlId");

                    b.ToTable("tentaminering");
                });

            modelBuilder.Entity("DAL.Entities.TentamineringLeeruitkomstEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beoordelingcriteria")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("LeeruitkomstId")
                        .HasColumnType("int");

                    b.Property<int>("TentamineringId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeeruitkomstId");

                    b.HasIndex("TentamineringId");

                    b.ToTable("tentaminering_leeruitkomst");
                });

            modelBuilder.Entity("DAL.Entities.EvlRevisieEntity", b =>
                {
                    b.HasBaseType("DAL.Entities.EvlEntity");

                    b.Property<int>("EvlId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasIndex("EvlId");

                    b.ToTable("evl");

                    b.HasDiscriminator().HasValue("EvlRevisieEntity");
                });

            modelBuilder.Entity("DAL.Entities.EindkwalificatieEntity", b =>
                {
                    b.HasOne("DAL.Entities.EvlEntity", null)
                        .WithMany("Eindkwalificaties")
                        .HasForeignKey("EvlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.LeeruitkomstEntity", b =>
                {
                    b.HasOne("DAL.Entities.EvlEntity", null)
                        .WithMany("Leeruitkomsten")
                        .HasForeignKey("EvlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.RubricCriteriumEntity", b =>
                {
                    b.HasOne("DAL.Entities.RubricEntity", null)
                        .WithMany("Beoordelingscriteria")
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.RubricEntity", b =>
                {
                    b.HasOne("DAL.Entities.TentamineringEntity", null)
                        .WithMany("Rubrics")
                        .HasForeignKey("TentamineringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.TentamineringEntity", b =>
                {
                    b.HasOne("DAL.Entities.EvlEntity", null)
                        .WithMany("Tentamineringen")
                        .HasForeignKey("EvlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.TentamineringLeeruitkomstEntity", b =>
                {
                    b.HasOne("DAL.Entities.LeeruitkomstEntity", "Leeruitkomst")
                        .WithMany()
                        .HasForeignKey("LeeruitkomstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.TentamineringEntity", null)
                        .WithMany("Leeruitkomsten")
                        .HasForeignKey("TentamineringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leeruitkomst");
                });

            modelBuilder.Entity("DAL.Entities.EvlRevisieEntity", b =>
                {
                    b.HasOne("DAL.Entities.EvlEntity", null)
                        .WithMany("Historie")
                        .HasForeignKey("EvlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.EvlEntity", b =>
                {
                    b.Navigation("Eindkwalificaties");

                    b.Navigation("Historie");

                    b.Navigation("Leeruitkomsten");

                    b.Navigation("Tentamineringen");
                });

            modelBuilder.Entity("DAL.Entities.RubricEntity", b =>
                {
                    b.Navigation("Beoordelingscriteria");
                });

            modelBuilder.Entity("DAL.Entities.TentamineringEntity", b =>
                {
                    b.Navigation("Leeruitkomsten");

                    b.Navigation("Rubrics");
                });
#pragma warning restore 612, 618
        }
    }
}
